//
// Created by Rafael Venetikides on 03/04/25.
//

#include "../../include/operations/power_operation.h"

void op_power(FILE *outAsm) {
    fprintf(outAsm, "op_pow_16bits:\n"
                    "    ; --- Entradas:\n"
                    "    ; Expoente em R17:R16 (valor inteiro > 0) em formato float16\n"
                    "    ; Base    em R19:R18 (float16)\n"
                    "    ;\n"
                    "    ; --- Saída:\n"
                    "    ; Resultado em R22:R23 (float16)\n"
                    "    \n"
                    "    ; Copia o expoente para o contador (R21:R20)\n"
                    "    MOV   R20, R16      ; contador low = expoente low\n"
                    "    MOV   R21, R17      ; contador high = expoente high\n"
                    "\n"
                    "    ; Inicializa resultado = 1.0 (float16: 0x3C00)\n"
                    "    LDI   R23, 0x3C     ; 1.0 - byte alto\n"
                    "    LDI   R22, 0x00     ; 1.0 - byte baixo\n"
                    "\n"
                    "    CLR   R1            ; Zera R1 para uso em op_sub_16bits\n"
                    "\n"
                    "pow_loop:\n"
                    "    ; Se o contador (R21:R20) é zero, fim do loop\n"
                    "    MOV   R26, R20    ; copia o byte baixo do contador para R26\n"
                    "    OR    R26, R21    ; R26 = R20 OR R21\n"
                    "    BREQ  end_pow     ; se R26 == 0, contador é zero → fim do loop\n"
                    "\n"
                    "    ; --- Multiplicação: resultado = resultado * base ---\n"
                    "    ; op_mult_16bits espera:\n"
                    "    ;   Operando1 em R19:R18\n"
                    "    ;   Operando2 em R17:R16\n"
                    "    ;\n"
                    "    ; A base original está em R19:R18 e o resultado atual em R22:R23.\n"
                    "    ; Para preservar a base, usamos registradores temporários.\n"
                    "\n"
                    "   PUSH R19\n"
                    "   PUSH R18\n"
                    "\n"
                    "    MOV   R25, R19     ; Guarda base (high) em R24\n"
                    "    MOV   R24, R18     ; Guarda base (low)  em R25\n"
                    "\n"
                    "    ; Coloca o resultado atual em R19:R18 (operando1)\n"
                    "    MOV   R19, R23\n"
                    "    MOV   R18, R22\n"
                    "\n"
                    "    ; Restaura a base para operando2\n"
                    "    MOV   R17, R25    ; base high\n"
                    "    MOV   R16, R24    ; base low\n"
                    "\n"
                    "    CALL  op_mult_16bits   ; Calcula produto: resultado em R22:R23\n"
                    "\n"
                    "    ; --- Salva o novo resultado (multiplicação) temporariamente ---\n"
                    "    PUSH  R22\n"
                    "    PUSH  R23\n"
                    "\n"
                    "    ; --- Decrementa o contador usando op_sub_16bits ---\n"
                    "    ; O contador está em R21:R20. Subtraímos 1.0 (representado em float16 como 0x3C00).\n"
                    "    MOV   R17, R21    ; Move contador high para R19\n"
                    "    MOV   R16, R20    ; Move contador low para R18\n"
                    "    LDI   R19, 0x3C   ; Carrega 1.0 - byte alto\n"
                    "    LDI   R18, 0x00   ; Carrega 1.0 - byte baixo\n"
                    "    CALL  op_sub_16bits   ; Executa (contador - 1.0), resultado em R23:R22\n"
                    "\n"
                    "    ; Atualiza o contador com o novo valor\n"
                    "    MOV   R21, R23\n"
                    "    MOV   R20, R22\n"
                    "\n"
                    "    ; --- Restaura o resultado da multiplicação ---\n"
                    "    POP   R23\n"
                    "    POP   R22\n"
                    "    POP   R18\n"
                    "    POP   R19\n"
                    "\n"
                    "    RJMP  pow_loop\n"
                    "\n"
                    "end_pow:\n"
                    "    ; Resultado final já está em R22:R23\n"
                    "    RET\n\n");
}
